# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/bin"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/binstalk-manifests"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/binstalk-types"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/binstalk"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/binstalk-downloader"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/detect-wasi"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/fs-lock"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/normalize-path"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/detect-targets"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/leon"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/leon-macros"
    schedule:
      interval: "daily"
