# Dependabot dependency version checks / updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/bin"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/binstalk"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/detect-wasi"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/flock"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/normalize-path"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/crates/detect-target"
    schedule:
      interval: "daily"
