[package]
name = "cargo-binstall"
description = "Rust binary package installer for CI integration"
repository = "https://bitbucket.org/nobodyxusdcdc/hello-world"
version = "0.12.0"
rust-version = "1.61.0"
authors = ["ryan <ryan@kurte.nz>"]
edition = "2021"
license = "GPL-3.0"

[package.metadata.binstall]
bin-dir = "{ bin }{ binary-ext }"

[[bin]]
name = "cargo-binstall"
