name: 'Install cargo-binstall'
description: 'Install the latest version of cargo-binstall tool'

runs:
  using: composite
  steps:
    - name: Install cargo-binstall
      if: runner.os != 'Windows'
      shell: sh
      run: |
        set -eu
        bash "${{ github.action_path }}/install-from-binstall-release.sh"
    - name: Install cargo-binstall
      if: runner.os == 'Windows'
      shell: powershell
      run: Set-ExecutionPolicy Unrestricted -Scope Process; iex "${{ github.action_path }}/install-from-binstall-release.ps1"
