pre-release-commit-message = "release: cargo-binstall v{{version}}"
tag-prefix = ""
tag-message = "cargo-binstall {{version}}"

# We wait until the release CI is done before publishing,
# because publishing is irreversible, but a release can be
# reverted a lot more easily.
publish = false

[[pre-release-replacements]]
file = "windows.manifest"
search = "^		version=\"[\\d.]+[.]0\""
replace = "		version=\"{{version}}.0\""
prerelease = false
max = 1
