name: Setup tools and cache
inputs:
  tools:
    description: Extra tools
    required: false
    default: ""
  indexcache:
    description: Enable index cache
    required: true
    default: true
    type: boolean
  buildcache:
    description: Enable build cache
    required: true
    default: true
    type: boolean

runs:
  using: composite
  steps:
  - name: Add just to tools to install
    run: echo "tools=just" >>$GITHUB_ENV
    shell: bash

  - name: Add inputs.tools to tools to install
    if: inputs.tools != ''
    env:
      inputs_tools: ${{ inputs.tools }}
    run: echo "tools=$tools,$inputs_tools" >>$GITHUB_ENV
    shell: bash

  - name: Install tools
    uses: taiki-e/install-action@v2
    with:
      tool: ${{ env.tools }}

  - name: Install rust toolchains
    run: just toolchain
    shell: bash

  - name: rustc version
    run: rustc -vV
    shell: bash

  - name: Retrieve RUSTFLAGS for caching
    if: inputs.indexcache || inputs.buildcache
    id: retrieve-rustflags
    run: |
      if [ -n "${{ inputs.buildcache }}" ]; then
          echo RUSTFLAGS="$(just print-rustflags)" >> "$GITHUB_OUTPUT"
      else
          echo RUSTFLAGS= >> "$GITHUB_OUTPUT"
      fi
    shell: bash

  - if: inputs.indexcache || inputs.buildcache
    uses: Swatinem/rust-cache@v2
    env:
      RUSTFLAGS: ${{ steps.retrieve-rustflags.outputs.RUSTFLAGS }}
