name: Setup tools and cache
inputs:
  tools:
    description: Extra tools
    required: false
    default: ""
  indexcache:
    description: Enable index cache
    required: true
    default: true
    type: boolean
  buildcache:
    description: Enable build cache
    required: true
    default: true
    type: boolean
  cache-suffix:
    description: Suffix for cache key
    required: false
    default: ""
runs:
  using: composite
  steps:
  - if: inputs.tools == ''
    name: Install just
    uses: taiki-e/install-action@v2
    with:
      tool: just
  - if: inputs.tools != ''
    name: Install just and tools
    uses: taiki-e/install-action@v2
    with:
      tool: just,${{ inputs.tools }}

  - if: inputs.indexcache
    name: Configure index cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
      key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-${{ inputs.cache-suffix }}
      restore-keys: |
        ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}-
        ${{ runner.os }}-cargo-index-

  - name: Install rust toolchains
    run: just toolchain
    shell: bash

  - name: rustc version
    run: rustc -vV | tee rustc-version
    shell: bash

  - if: inputs.buildcache
    name: Configure sccache
    uses: mozilla-actions/sccache-action@v0.0.2
    with:
      version: "v0.4.0-pre.10"

  - if: inputs.buildcache
    name: Export env for sccache to work
    shell: bash
    run: |
      echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
      echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

  - if: inputs.buildcache
    name: Configure post run for sccache stat
    uses: webiny/action-post-run@3.0.0
    with:
      run: ${SCCACHE_PATH} --show-stats
