name: Tag a release
on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  make-tag:
    runs-on: ubuntu-latest
    # the commit message will look like: `release: v{version} (#{pr-number})`
    if: "startsWith(github.event.head_commit.message, 'release: v')"
    steps:
      - name: Extract tag from commit message
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          set -euxo pipefail

          message="$(head -n1 <<< "$COMMIT_MESSAGE")"
          version="$(cut -d ' ' -f 2 <<< "${message}")"
          echo "CUSTOM_TAG=${version}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - name: Push release tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ env.CUSTOM_TAG }}
          tag_prefix: ''
