name: Release TEST
on:
  pull_request:

jobs:
  info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      notes: ${{ fromJSON(steps.notes.outputs.notes_json) }}
    env:
      COMMIT_MESSAGE: "release: v0.11.0 (#234)"
    steps:
    - uses: actions/checkout@v2
    - name: Extract tag from commit message
      id: version
      run: ./ci-scripts/extract-tag-from-release-commit.sh
    - name: Extract release notes
      id: notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO: ${{ github.repository }}
      run: ./ci-scripts/extract-release-notes.sh

  tag:
    needs: info
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push release tag
      if: false
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag: ${{ needs.info.outputs.version }}
        tag_prefix: 'test-'

  build:
    needs: info # not really, but just so it fails fast
    uses: ./.github/workflows/build.yml
    with:
      for_release: true

  release:
    needs:
      - info
      - tag
      - build
    name: Package and release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get outputs
      uses: actions/download-artifact@v3
      with:
        path: outputs/

    - name: Pack archives
      run: ./ci-scripts/pack-release-archives.sh

    - name: Write release notes
      env:
        notes: ${{ needs.info.outputs.notes }}
      run: echo "$notes" > outputs/NOTES

    - name: Write release version
      env:
        version: ${{ needs.info.outputs.version }}
      run: echo "$version" > outputs/VERSION

    - name: Upload release bits
      uses: actions/upload-artifact@v3
      with:
        retention-days: 1
        name: release-bits
        path: |
          outputs/cargo-binstall-*.zip
          outputs/cargo-binstall-*.tgz
          outputs/NOTES
          outputs/VERSION
